package jetpack.tutorial.cryptoapp.features.crypto.domain.usecase.get_crypto_intra_info

import jetpack.tutorial.cryptoapp.core.networking.utils.FlowResultUseCase
import jetpack.tutorial.cryptoapp.features.crypto.domain.model.CryptoIntraInfoModel

interface GetCryptoIntraInfoUseCase: FlowResultUseCase<CryptoIntraInfoParam,CryptoIntraInfoModel>